version: '3.3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    restart: unless-stopped
    volumes:
      - pg_data:/var/lib/postgresql/data
  back:
    image: mvobr/gen_pass_back
    env_file: .env
    restart: unless-stopped
    depends_on:
      - db
  front:
    image: mvobr/gen_pass_front
    env_file: .env
    volumes:
      - static:/app/result_build/build

  nginx:
    image: nginx:1.19.3
    restart: unless-stopped
    ports:
      - "8051:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
