version: '3.3'

volumes:
  static:

services:
  back:
    image: mvobr/gen_pass_back
    env_file: .env
  front:
    image: mvobr/gen_pass_front
    env_file: .env
    volumes:
      - static:/app/result_build/build
  nginx:
    image: nginx:1.19.3
    ports:
      - "8052:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
